sonata_admin:
    # utilisation du composant bootstrap
    options:
        use_bootlint:    true # enable Bootlint
    title: 'Sonata Admin'
    # all templates
    templates:
        user_block: 'Admin/Core/user_block.html.twig'
        add_block: 'Admin/Core/add_block.html.twig'
        # page global du dashboard
        layout: 'Admin/standard_layout.html.twig'
        #ajax: 'Admin/ajax_layout.html.twig'
        dashboard: 'Admin/Core/dashboard.html.twig'
        search: 'Admin/Core/search.html.twig'
        list: 'Admin/CRUD/list.html.twig'
        filter: 'Admin/Form/filter_admin_fields.html.twig'
        show: 'Admin/CRUD/show.html.twig'
        show_compare: 'Admin/CRUD/show_compare.html.twig'
        edit: 'Admin/CRUD/edit.html.twig'
        preview: 'Admin/CRUD/preview.html.twig'
        history: 'Admin/CRUD/history.html.twig'
        acl: 'Admin/CRUD/acl.html.twig'
        history_revision_timestamp: 'Admin/CRUD/history_revision_timestamp.html.twig'
        action: 'Admin/CRUD/action.html.twig'
        select: 'Admin/CRUD/list__select.html.twig'
        list_block: 'Admin/Block/block_admin_list.html.twig'
        search_result_block: 'Admin/Block/block_search_result.html.twig'
        short_object_description: 'Admin/Helper/short-object-description.html.twig'
        delete: 'Admin/CRUD/delete.html.twig'
        batch: 'Admin/CRUD/list__batch.html.twig'
        batch_confirmation: 'Admin/CRUD/batch_confirmation.html.twig'
        inner_list_row: 'Admin/CRUD/list_inner_row.html.twig'
        outer_list_rows_mosaic: 'Admin/CRUD/list_outer_rows_mosaic.html.twig'
        outer_list_rows_list: 'Admin/CRUD/list_outer_rows_list.html.twig'
        outer_list_rows_tree: 'Admin/CRUD/list_outer_rows_tree.html.twig'
        base_list_field: 'Admin/CRUD/base_list_field.html.twig'
        pager_links: 'Admin/Pager/links.html.twig'
        pager_results: 'Admin/Pager/results.html.twig'
        tab_menu_template: 'Admin/Core/tab_menu_template.html.twig'
        knp_menu_template: 'Admin/Menu/sonata_menu.html.twig'
        form_theme: []
        filter_theme: []

    assets:
        stylesheets:

            # The default stylesheet list:
            - bundles/sonataadmin/app.css

        # stylesheet paths to add to the page in addition to the list above
        extra_stylesheets: []

        # stylesheet paths to remove from the page
        remove_stylesheets: []

        javascripts:

            # The default javascript list:
            - bundles/sonataadmin/app.js

        # javascript paths to add to the page in addition to the list above
        extra_javascripts: []

        # javascript paths to remove from the page
        remove_javascripts: []

    dashboard:
        blocks:
            -   # block 1
                position: top #position
                type: sonata.block.service.text #type de bloc (text HTML)
                settings:   #configurationn du type de bloc (text HTML)
                    content: >
                        <h2>BIENVENUE</h2>
            -   # block 2
                position: left                           
                class:    col-lg-12                         
                type:     block.count.article    
            -   # block 2
                position: bottom                           
                class:    col-lg-12 shadow-sm rounded bg-white                    
                type:     sonata.admin.block.admin_list     
                settings:
                    groups: [Nos articles]   

            -   # block 3
                position: bottom     
                class:    hidden            
                type:     sonata.admin.block.admin_list     
                settings:
                    groups: [Configurations]   
            -   # block 4
                position: bottom     
                class:    hidden             
                type:     sonata.admin.block.admin_list     
                settings:
                    groups: [Utilisateurs]   
            -   # block 5
                position: bottom     
                class:    hidden             
                type:     sonata.admin.block.admin_list   
            -   # block 6
                position: top     
                class:    col-lg-4             
                type:     block.current.user  
                # Ajouter un lien sans menu parrent

        # Declaration of group of Model/items/services
        groups:
                    Nos articles:
                        items:
                            - admin.articles                    
                    Configurations: 
                        items:
                            - admin.categories
                            - admin.baniere
                    Utilisateurs: 
                        items:
                            - admin.user

    extensions:
            app.articles.extension:
                admins:     #specify one or more admin service ids to which the Extension should be added.
                    - admin.articles
                priority: 1	#Can be a positive or negative integer. The higher the priority, the earlier it was executed.

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
    