sonata_block:
    default_contexts: [sonata_page_bundle]

sonata_admin:
    assets:
        extra_javascripts:
            - bundles/sonatapage/app.js
            - assets/all.js
        extra_stylesheets:
            - bundles/sonatapage/app.css
            - assets/all.css
            - assets/app.css

# https://docs.sonata-project.org/projects/SonataPageBundle/en/4.x/reference/advanced_configuration/
sonata_page:
    skip_redirection: false # Skip asking Editor to redirect
    #slugify_service: sonata.page.slugify.cocur # old BC value is sonata.core.slugify.native
    multisite: host #~
    use_streamed_response: true  # set the value to false in debug mode or if the reverse proxy does not handle streamed response

    # mes service  page bundles
    class:
        page: App\Entity\SonataPagePage
        snapshot: App\Entity\SonataPageSnapshot
        block: App\Entity\SonataPageBlock
        site: App\Entity\SonataPageSite

    router_auto_register:
        enabled: true
        priority: 150

    ignore_route_patterns:
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^_(.*)          # ignore symfony routes

    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc

    ignore_uri_patterns:
        - ^/admin\/   # ignore admin route, ie route containing 'admin'

    page_defaults:
        homepage: {decorate: false, enabled: true} # disable decoration for homepage, key - is a page route

    #https://docs.sonata-project.org/projects/SonataPageBundle/en/4.x/reference/page_composer/
    default_template: default # template key from templates section, used as default for pages
    templates:

        webgroup:
            #path: '@SonataPage/layout.html.twig' #'base.html.twig'
            path: 'base.html.twig'
            name: 'webgroup theme'

        default:
            path: '@SonataPage/layout.html.twig'
            name: 'default'
            containers:
                header:
                    name: Header
                content_top:
                    name: Top content
                content:
                    name: Main content
                content_bottom:
                    name: Bottom content
                footer:
                    name: Footer
            matrix:
                layout: |
                    HHHHHHHH
                    TTTTTTTT
                    TTTTTTTT
                    CCCCCCCC
                    CCCCCCCC
                    BBBBBBBB
                    BBBBBBBB
                    FFFFFFFF

                mapping:
                    H: header
                    T: content_top
                    C: content
                    B: content_bottom
                    F: footer

        2columns:
            path: '@SonataPage/2columns_layout.html.twig'
            name: '2 columns layout'
            inherits_containers: default
            containers:
                left_col:
                    name: Left column
                    blocks:
                        - sonata.media.block.media
                        - sonata.media.block.gallery
                        - sonata.media.block.feature_media
                content:
                    name: Main content
                    blocks:
                        - sonata.media.block.media
                right_col:
                    name: Right column
                    blocks:
                        - sonata.news.block.recent_posts
                        - sonata.order.block.recent_orders
                        - sonata.product.block.recent_products
            matrix:
                layout: |

                    HHHHHHHHHH
                    TTTTTTTTTT
                    TTTTTTTTTT
                    LLLCCCCRRR
                    LLLCCCCRRR
                    BBBBBBBBBB
                    BBBBBBBBBB
                    FFFFFFFFFF

                mapping:
                    H: header
                    T: content_top
                    L: left_col
                    R: right_col
                    C: content
                    B: content_bottom
                    F: footer

#    3columns:
#        path: '@ApplicationSonataPage/3columns_layout.html.twig'
#        name: '3 columns layout'
#        containers:
#            left_col:
#                name: Left column
#                blocks:
#                    - sonata.media.block.media
#                    - sonata.media.block.gallery
#                    - sonata.media.block.feature_media
#            mid_col:
#                name: Left column
#                blocks:
#                    - sonata.media.block.media
#                    - sonata.media.block.gallery
#                    - sonata.media.block.feature_media
#            right_col:
#                name: Right column
#                blocks:
#                    - sonata.news.block.recent_posts
#                    - sonata.order.block.recent_orders
#                    - sonata.product.block.recent_products
#        matrix:
 #           layout: |
#                LLLMMMMRRR
#                LLLMMMMRRR
#                LLLMMMMRRR
#                LLLMMMMRRR
#                LLLMMMMRRR
#
#            mapping:
#               L: left_col
#               R: right_col
#               M: mid_col



    direct_publication: '%kernel.debug%' # or %kernel.debug% if you want to publish in dev mode (but not in prod), in prod put false

    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error
