sonata_admin:

    # utilisation du composant bootstrap
    options:
        use_bootlint:    true # enable Bootlint
    title: 'Sonata Admin'
    # all templates
    templates:
        # page global du dashboard
        #layout: 'Admin/standard_layout.html.twig'
        form_theme: []
        filter_theme: []

    assets:
        #Assets of sonatapagebundle
        extra_javascripts:
            - bundles/sonatapage/sonata-page.back.min.js
            - bundles/sonatapage/app.js
            - bundles/fosckeditor/ckeditor.js
        extra_stylesheets:
            - bundles/sonatapage/sonata-page.back.min.css
            - bundles/sonatapage/app.css

        stylesheets:
            # The default stylesheet list:
            - bundles/sonataadmin/app.css

        # stylesheet paths to remove from the page
        remove_stylesheets: []

        javascripts:
            # The default javascript list:
            - bundles/sonataadmin/app.js

        # javascript paths to remove from the page
        remove_javascripts: []

    dashboard:
        blocks:
            -   # block 1
                position: top #position
                type: sonata.block.service.text #type de bloc (text HTML)
                settings:   #configurationn du type de bloc (text HTML)
                    content: >
                        <h2>BIENVENUE</h2>
            -   # block 2
                position: left                           
                class:    col-lg-12                         
                type:     block.count.article    
            -   # block 2
                position: bottom                           
                class:    col-lg-12 shadow-sm rounded bg-white                    
                type:     sonata.admin.block.admin_list     
                settings:
                    groups: [Nos articles]   

            -   # block 3
                position: bottom     
                class:    hidden            
                type:     sonata.admin.block.admin_list     
                settings:
                    groups: [Les plus]   
            -   # block 4
                position: bottom     
                class:    hidden             
                type:     sonata.admin.block.admin_list     
                settings:
                    groups: [Utilisateurs]   
            -   # block 5
                position: bottom     
                class:    hidden             
                type:     sonata.admin.block.admin_list   
            -   # block 6
                position: top     
                class:    col-lg-4             
                type:     block.current.user  
                # Ajouter un lien sans menu parrent
            -   # block 8
                position: bottom     
                class:    hidden             
                type:     sonata.admin.block.admin_list     
                settings:
                    groups: [Gestion des blocks]   
            -   # block 9
                position: bottom     
                class:    hidden             
                type:     sonata.admin.block.admin_list     
                settings:
                    groups: [Configuration du site]   

        # Declaration of group of Model/items/services
        groups:
                    Nos articles:
                        items:
                            #- admin.articles 
                            - admin.articles_custom   
                            - admin.page                

                    Les plus: 
                        items:
                            - admin.categories
                            - admin.baniere

                    Utilisateurs: 
                        items:
                            - admin.user
                        roles: ['ROLE_SUPER_ADMIN']

                    Gestion des blocks: 
                        items:
                            - sonata.page.admin.shared_block
                            #- sonata.page.admin.base.block
                            #- sonata.page.admin.block
                        roles: ['ROLE_SUPER_ADMIN']

                    Configuration du site: 
                        items:
                            - sonata.page.admin.site
                            - sonata.page.admin.snapshot
                        roles: ['ROLE_SUPER_ADMIN']

    extensions:
            app.articles.extension:
                admins:     #specify one or more admin service ids to which the Extension should be added.
                    - admin.articles
                priority: 1	#Can be a positive or negative integer. The higher the priority, the earlier it was executed.

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
    